services:
  web:
    build: .
    container_name: timesheet_web
    command: >
      sh -c "python manage.py migrate --settings=familyhub_timesheet.settings.test &&
             python manage.py collectstatic --noinput --settings=familyhub_timesheet.settings.test &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 familyhub_timesheet.wsgi:application"
    volumes:
      - .:/app
      - static_files:/app/staticfiles
      - media_files:/app/mediafiles
    ports:
      - "8080:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DJANGO_ENVIRONMENT=production
    networks:
      - timesheet_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  static_files:
    driver: local
  media_files:
    driver: local

networks:
  timesheet_network:
    driver: bridge
